/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RandomWinnerGame } from "./RandomWinnerGame";
export * as factories from "./factories";
export { RandomWinnerGame__factory } from "./factories/RandomWinnerGame__factory";
export const RANDOM_WINNER_GAME_ADDRESS = "0xed4d3525dfc7ac38c36e7d7234996b1933b6360d";
